# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        pre_command: |
          # gcc
          sudo apt install gcc libc6-dev
          
          # x11
          sudo apt install libx11-dev xorg-dev libxtst-dev
          
          # Clipboard
          sudo apt install xsel xclip
          
          #
          # Bitmap
          sudo apt install libpng++-dev
          
          # GoHook
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev
  release-linux-arm64:
    name: release linux/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: arm64
        pre_command: |
          # gcc
          sudo apt install gcc libc6-dev
          
          # x11
          sudo apt install libx11-dev xorg-dev libxtst-dev
          
          # Clipboard
          sudo apt install xsel xclip
          
          #
          # Bitmap
          sudo apt install libpng++-dev
          
          # GoHook
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        pre_command: |
          # gcc
          sudo apt install gcc libc6-dev
          
          # x11
          sudo apt install libx11-dev xorg-dev libxtst-dev
          
          # Clipboard
          sudo apt install xsel xclip
          
          #
          # Bitmap
          sudo apt install libpng++-dev
          
          # GoHook
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

  release-windows-arm64:
    name: release windows/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: arm64
        pre_command: |
          # gcc
          sudo apt install gcc libc6-dev
          
          # x11
          sudo apt install libx11-dev xorg-dev libxtst-dev
          
          # Clipboard
          sudo apt install xsel xclip
          
          #
          # Bitmap
          sudo apt install libpng++-dev
          
          # GoHook
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

  release-darwin-arm64:
    name: release darwin/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: darwin
        goarch: arm64
        pre_command: |
          # gcc
          sudo apt install gcc libc6-dev
          
          # x11
          sudo apt install libx11-dev xorg-dev libxtst-dev
          
          # Clipboard
          sudo apt install xsel xclip
          
          #
          # Bitmap
          sudo apt install libpng++-dev
          
          # GoHook
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: darwin
        goarch: amd64
        pre_command: |
          # gcc
          sudo apt install gcc libc6-dev
          
          # x11
          sudo apt install libx11-dev xorg-dev libxtst-dev
          
          # Clipboard
          sudo apt install xsel xclip
          
          #
          # Bitmap
          sudo apt install libpng++-dev
          
          # GoHook
          sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev

